Fixed _FILE_OFFSET_BITS on 32-bit systems
libuv/libuv pull request #3065
Opened 2020-12-10 10:27 UTC by nesbox

UV doesn't link on the 32-bit Unix system.
```
lib/libuv_a.a(process.c.o): In function `uv_spawn':
process.c:(.text+0x368): undefined reference to `fcntl64'
lib/libuv_a.a(core.c.o): In function `uv__nonblock_fcntl':
core.c:(.text+0x6ec): undefined reference to `fcntl64'
core.c:(.text+0x744): undefined reference to `fcntl64'
lib/libuv_a.a(core.c.o): In function `uv__cloexec_fcntl':
core.c:(.text+0x798): undefined reference to `fcntl64'
core.c:(.text+0x7ec): undefined reference to `fcntl64'
lib/libuv_a.a(pipe.c.o):pipe.c:(.text+0x2a0): more undefined references to `fcntl64' follow
collect2: error: ld returned 1 exit status
```

2020-12-10 12:22 UTC, bnoordhuis requested changes
Thanks for the pull request but this isn't correct. Libuv should use 64 bits `off_t` when available - which is normally always, even on 32 bits system.

On what kind of system are you getting these errors?

2020-12-10 12:31 UTC, nesbox commented
I'm getting this when cross-compile Raspberry Pi on Ubuntu.
https://github.com/nesbox/TIC-80/runs/1529777284?check_suite_focus=true#step:4:411
Seems we have to autodetect `_FILE_OFFSET_BITS=64` someway...

2020-12-11 09:05 UTC, bnoordhuis commented
If it's only complaining about `fcntl64` then I suspect it's something else, otherwise I'd expect to also see e.g. `stat64` in there.

2020-12-14 13:00 UTC, nesbox commented
I've added `_FILE_OFFSET_BITS=64` detection via `try_compile` function in Cmake.
Could you please review it now?
Thank you.

2020-12-14 22:58 UTC, bnoordhuis commented
I still don't think this is the right approach, see also my previous comment.

I can't say for sure but the fact that you're the first to run into this, even though libuv has been compiled with large file support ever since its inception, makes me suspect it's an issue local to your system or toolchain.

What's more, large file support has been pretty much the standard on Linux for almost 20 years now (kernel 2.4.0, released in January 2001 - it was a big thing at the time.) It's almost inconceivable that your kernel or libc doesn't support it.

2020-12-15 05:46 UTC, nesbox commented
I'm using the latest Raspbian image to build http://downloads.raspberrypi.org/raspbian/
Ok, I'll stay on my fork then, maybe the problem is on my side.
Thanks.

2020-12-15 05:46 UTC, closed without merging