unix,win: use static_assert when available
libuv/libuv pull request #3189
Opened 2021-05-25 16:20 UTC by bnoordhuis

Fixes: https://github.com/libuv/libuv/issues/3131

2021-05-25 18:38 UTC, alzix commented
please note `static_assert(...)` requires an include to `assert.h` when building with `Apple clang version 12.0.0 (clang-1200.0.32.29)`.
This is what i found during my #3186 testing.

2021-05-25 19:05 UTC, bnoordhuis commented
uv-common.h includes assert.h so that should be no problem. I added a fix for android because it seems to be missing static_assert.

2021-05-26 01:00 UTC, cjihrig approved these changes

2021-05-26 06:36 UTC, bnoordhuis commented
> this is where configure time detection comes handy

I'd have to do it in two places though: CMakeLists.txt and autoconf.ac.

2021-05-27 14:49 UTC, vtjnash approved these changes
CI: https://ci.nodejs.org/job/libuv-test-commit/2158/

2021-05-27 15:01 UTC, vtjnash requested changes
This seems to have fared pretty poorly in CI

2022-02-13 06:55 UTC, vtjnash commented on src/uv-common.h
> +#define STATIC_ASSERT(expr) static_assert(expr, #expr)
```suggestion
/* C11 defines static_assert to be a macro which calls _Static_assert. */
#if defined(static_assert)
#define STATIC_ASSERT(expr) static_assert(expr, #expr)
```

2023-01-18 04:26 UTC, vtjnash approved these changes

2023-01-18 04:26 UTC, merged