Reap all processes if getpid() == 1
libuv/libuv pull request #3199
Opened 2021-06-10 02:06 UTC by giannitedesco

This is useful to allow libuv users to run in containers or as init systems (effectively the same thing).

2021-06-10 16:50 UTC, vtjnash requested changes
I think this would break any process that uses libuv as a plugin, or uses plugin with libuv. We need to only ever reap children we know about, which is tricky. There was a proposal to add the necessary functionally as a feature to the linux kernel, but it was abandoned ("undesirable"): http://lkml.iu.edu/hypermail/linux/kernel/0812.3/00647.html

However, it can perhaps be emulated in a buggy way by recording all forks and adding them to the list here until notification of their exit (assuming no PR_SET_CHILD_SUBREAPER happened): https://stackoverflow.com/a/15614850/1712368

2021-06-11 00:49 UTC, giannitedesco commented
Hi, thanks for the review, that was quick!

Hrm, I think tracking all the children of processes we spawn is very involved. I mean, it might be a really nice solution for use-cases where it's necessary: ie. libuv is a library among many and they are all forking processes, but somehow only libuv is setting up a signal handler (? perhaps you could describe the scenario in more detail because i'm not sure how this is meant to work?).

But, the point is, I think there is also a use-case for a dumber reaper for processes where libuv is _the_ event-loop and process spawner.

The way python asyncio handles all this is by having a child-reaping policy: https://docs.python.org/3/library/asyncio-policy.html#asyncio.AbstractChildWatcher

What's on offer there is:

- safe: catch `SIGCHLD`, reap processes we know about (as libuv currently does)
- fast: catch `SIGCHLD`, reap all processes (the new mode I'm proposing)
- pidfd: don't register for signals, listen to events on pidfd's instead (so as not to interfere with other libraries that also want to catch `SIGCHLD`)
- some other, more specialised approaches, but nothing as involved as what you describe although an escape hatch is there for people to implement policy plugins

Would it make more sense for libuv to pursue something more like this? I mean, keep the current default, but opt in to different policies depending on the use-case.

2021-06-11 08:24 UTC, giannitedesco commented
> libuv is a library among many and they are all forking processes, but somehow only libuv is setting up a signal handler (? perhaps you could describe the scenario in more detail because i'm not sure how this is meant to work?)

Ah, I think you are talking about the case where some other library runs its own process and expects to be able to `waitpid()` on it later but if libuv `SIGCHLD` handler reaps that process then it will lead to erroneous behaviour.

Yes.

Well, it strikes me that this is probably why Linux introduced `CLONE_PIDFD`, to effectively allow for libraries to create processes which do not generate signals in this way. But that isn't a great answer for libuv which has to support whatever other libraries already exist, as well as windows.

2023-08-21 11:54 UTC, bnoordhuis commented
This PR has conflicts and going by the conversation won't get merged as-is anyway so I'll go ahead and close it.

2023-08-21 11:54 UTC, closed without merging