Add an example to uv_timeval64_t
libuv/libuv pull request #3568
Opened 2022-03-19 08:27 UTC by krishna116

It is used to denote how to convert uv_timeval64_t to human readable string.

2022-03-21 18:56 UTC, vtjnash requested changes
I don't think we have any content like this, and I am not certain I want to recommend use of non-libuv functions such as `localtime` and `strftime`. It could be added to the uvbook code/ folder however.

2022-03-23 07:25 UTC, krishna116 commented
Because there are many  functions, for example, 
C11 has https://en.cppreference.com/w/c/chrono/timespec
C++11 has std::chrono,
unix has gettimeofday(),
libuv has created this one,
and so on.

All of these can generate timestamp, but the function for converting them to human readable string is also not the same and not uniform.
so, I think it may be necessary to tell people how to convert it to human readable string, not just a tutorial.

thank you.

2022-03-23 15:42 UTC, vtjnash commented
Yes, there are many such functions, and this example does not use libuv to choose one. While `strftime` and `localtime` are C89, we are not documenting C here, but libuv.

2022-03-25 11:27 UTC, krishna116 commented
Ok, so it is closed.

2022-03-25 11:27 UTC, closed without merging