uv: move queue.h from src to include/uv
libuv/libuv pull request #3771
Opened 2022-09-24 17:32 UTC by pkarashchenko

queue.h file name is frequently used accross many projects. Move queue.h from src to include/uv to avoid picking a wrong file while integrating libuv with third party code.

2022-09-24 21:47 UTC, vtjnash requested changes
This seems strictly much worse for integration, since it moves it from a private inaccessible file to a publicly installedd header?

2022-09-25 04:31 UTC, pkarashchenko commented
> This seems strictly much worse for integration, since it moves it from a private inaccessible file to a publicly installedd header?

But there is not much difference from `tree.h`. I mean that in `queue.h` there is no private specific data or definitions and nothing that prevents usage publicly.

2022-09-25 05:21 UTC, bnoordhuis commented
tree.h is in include/ because include/uv/win.h uses RB_ENTRY. Nothing from queue.h is directly used in include/ however.

2022-09-25 05:42 UTC, pkarashchenko commented
> tree.h is in include/ because include/uv/win.h uses RB_ENTRY. Nothing from queue.h is directly used in include/ however.

That is true.
Let me think more about how the issue can be handled. The main reason why I opened this PR is to change from `#include "queue.h` to `#include "xxx/queue.h` so if there is another path containing `queue.h` passed as `-I` to compiler the correct file will be included. But seems some other option should be considered.

2022-09-25 05:53 UTC, bnoordhuis commented
When would that be an issue? The src/ directory is always first on the include path when you use libuv's build scripts. You're responsible for that if you use your own scripts, of course.

2022-09-25 07:06 UTC, pkarashchenko commented
> When would that be an issue? The src/ directory is always first on the include path when you use libuv's build scripts. You're responsible for that if you use your own scripts, of course.

Yeah. I re-examined my initial issue and indeed it is a bit different. I'm integrating with an environment that re-implements a standard library and one of the standard includes `#include <queue.h>`. So libuv file is picked instead of the environment file.

Closing this PR and will see how to fix this on my end.

2022-09-25 07:06 UTC, closed without merging