win: fix fstat for pipes and character files
libuv/libuv pull request #3811
Opened 2022-11-03 16:32 UTC by StefanStojanovic

On Windows, when calling `uv_fs_fstat` for `stdin`, `stdout` or `stderr` file descriptors, an error is thrown, because the call to `NtQueryInformationFile` fails with Nt status code `0xC0000010 (STATUS_INVALID_DEVICE_REQUEST)`. Probably one of the easiest ways to reproduce this would be to run the following command in Node.JS `require('fs').fstatSync(0)`. At the same time, this is a completely regular script to run on Linux as it will fetch stdin stats and throws no errors.

The solution is based on the way Windows Kit implements `fstat` in `CRT` (more details on that can be found in Windows Kit sources eg. `C:\Program Files (x86)\Windows Kits\10\Source\10.0.19041.0\ucrt\filesystem\stat.cpp`). When dealing with regular disk files, there are no changes ie. previously existing logic is used. However, when a character or pipe file is detected, a new logic to fill the response data is triggered.

A new test is added to check this behavior and it's called `fs_fstat_stdio`. It runs on all platforms, although validation on Windows is the most detailed one.

Refs: https://github.com/nodejs/node/issues/40006

2022-11-06 19:20 UTC, vtjnash requested changes
`fd` is not always available, which is why we use the native Win32 APIs rather than the msvcrt compatibility shim--and there is already a uv_guess_handle function for getting this information in libuv

2022-11-15 22:30 UTC, StefanStojanovic commented
Implementation is changed to use `uv_guess_handle`. Even though no changes were planned in `fs__stat_handle`, they turned out to be required in order to cover null device usage eg. `node script.js > nul`

2022-11-25 10:52 UTC, StefanStojanovic commented
@vtjnash is there something else I should do here to help move this forward?

2022-11-25 17:15 UTC, vtjnash reviewed
Sorry for the delay. I had been meaning to look up what reasonable defaults would look like for these structs to satisfy what properties an application might expect to see here

2022-11-29 19:20 UTC, StefanStojanovic commented on src/win/fs.c
> +    statbuf->st_dev = (uint64_t)fd;
Unfortunately, that link doesn't show the full list. I've tested with "CONIN$" and "CONOUT$", and they are `FILE_DEVICE_CONSOLE (0x50)`. I've pushed a commit with that change and also adapted tests to your previous changes.

2022-11-29 20:35 UTC, vtjnash commented on src/win/fs.c
> +    statbuf->st_dev = (uint64_t)fd;
Awesome, thanks for checking!

2022-11-29 20:38 UTC, vtjnash approved these changes

2022-11-29 20:38 UTC, vtjnash commented on src/win/fs.c
> +    statbuf->st_ino = (uint64_t)uv_get_osfhandle(fd);
minor nit: I missed that this value is already one of the arguments
```suggestion
    statbuf->st_ino = (uint64_t) handle;
```

2022-11-29 22:46 UTC, merged